networks:
  default:
    driver: bridge
    name: project2
    # external: true # i created network already usign docker network create roboshop

volumes:
  mongodb:
  redis:
  mysql:
  rabbitmq:
services: 
  mongodb:
    image: anandj9949/mongodb:v1
    container_name: mongodb
    volumes:
    - mongodb:/data/db
  catalogue:
    image: anandj9949/catalogue:v1
    container_name: catalogue
    depends_on:
    - mongodb
  redis:
    image: redis:7.0
    container_name: redis
    volumes:
    - redis://data
  user:
    image: anandj9949/user:v1
    container_name: user
    depends_on:
    - redis
    - mongodb
  cart:
    image: anandj9949/cart:v1
    container_name: cart
    depends_on:
    - catalogue
    - redis
  mysql:
    image: anandj9949/mysql:v1
    container_name: mysql
    volumes:
    - mysql:/var/lib/mysql
  shipping:
    image: anandj9949/shipping:v1
    container_name: shipping
    depends_on:
    - mysql
    - cart
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: project2
      RABBITMQ_DEFAULT_PASS: project123
    volumes:
    - rabbitmq:/var/lib/rabbitmq
  payment:
    image: anandj9949/payment:v1
    container_name: payment
    environment:
      CART_HOST: cart
      CART_PORT: 8080
      USER_HOST: user
      USER_PORT: 8080
      AMQP_HOST: rabbitmq
      AMQP_USER: project1
      AMQP_PASS: project123
    depends_on:
      - rabbitmq
      - cart
      - user

  frontend:
    image: anandj9949/frontend:v1
    container_name: frontend
    ports:
    - "80:80" 
    depends_on:
    - catalogue
    - user
    - payment
    - shipping
    - cart